### ISSUE TITLE
wrong type?

### ISSUE THREAD

**Issue by website19880927** [voice-engine/wenwen#1]
Hi,when I install the code as the tutorial, and run the offline.py ,it told me wrong type in 
self._lib.mobvoi_recognizer_set_params('mobvoi_folder', os.path.join(os.path.dirname(__file__), '.mobvoi'))
and I am new in the code ,and still got no idea of the problem and I also signed a KEY on 
the official Site ,and filled that in ,still no response? same error~~ 

![image](https://user-images.githubusercontent.com/40953486/53287790-4440fd80-37bc-11e9-804f-64fa837c97a7.png)

**Comment by xiongyihui** [comment]
Are you using python3? A few workarounds are needed to encode `str` in python3.

**Comment by xiongyihui** [comment]
There is a branch for python3 now. Check it out at https://github.com/voice-engine/wenwen/tree/python3
